site_name: OBMS Documentation
site_url: "https://docs.getobms.com"
repo_url: "https://github.com/OBMS-Open-Business-Management-Software/core"
repo_name: OBMS Core
theme:
  name: material
  logo: assets/full.logo.svg
  palette:
    primary: custom
    accent: custom
  font:
    text: Space Grotesk
  icon:
    repo: fontawesome/brands/github
copyright: "© 2025 OBMS (Open Business Management Software). All rights reserved."
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OBMS-Open-Business-Management-Software/core
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Getting Started:
    - Introduction: getting-started/intro.md
    - Prerequisites: getting-started/prerequisites.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Modules: modules.md
  - User Guide:
    - Introduction: user_guide/intro.md
  - Admin Guide:
    - Introduction: admin_guide/intro.md
    - User Management: admin_guide/user_management.md
    - REST API: admin_guide/api.md
    - OAUTH Server: admin_guide/oauth.md
    - WebDAV Server: admin_guide/webdav.md
  - Developer Guide:
    - Introduction: developer_guide/intro.md
    - Products: developer_guide/products.md
    - Payment Gateways: developer_guide/payment_gateways.md
  - License: misc/license.md
  - Changelog: misc/changelog.md

