site_name: OBMS
site_url: "https://docs.obms.one"
repo_url: "https://github.com/OBMS-Open-Business-Management-Software/core"
repo_name: OBMS Core
theme:
  name: material
  custom_dir: overrides
  logo: assets/full.logo.svg
  favicon: assets/full.favicon.svg
  palette:
    primary: custom
    accent: custom
  font:
    text: Space Grotesk
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - navigation.sections
    - content.code.copy
  experimental: true
copyright: "© 2025 OBMS (Open Business Management Software). All rights reserved."
plugins:
  - search
  - swagger-ui-tag
  - macros:
      macros_file: "mkdocs_macros.py"
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OBMS-Open-Business-Management-Software/core
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EZPkVqpvy9
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-NXVCZ74CM7
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
extra_javascript:
  - js/extra.js
nav:
  - Documentation:
    - Getting Started:
      - Prerequisites: docs/getting-started/prerequisites.md
      - Installation:
        - Bare Metal: docs/getting-started/installation/bare_metal.md
        - Docker: docs/getting-started/installation/docker.md
        - Kubernetes: docs/getting-started/installation/kubernetes.md
      - Default Login: docs/getting-started/default_login.md
      - Instance Configuration: docs/getting-started/configuration.md
    - Modules: docs/modules.md
    - User Guide:
      - Introduction: docs/user_guide/intro.md
    - Admin Guide:
      - Introduction: docs/admin_guide/intro.md
      - User Management: docs/admin_guide/user_management.md
      - OAUTH Server: docs/admin_guide/oauth.md
      - WebDAV Server: docs/admin_guide/webdav.md
    - Developer Guide:
      - Introduction: docs/developer_guide/intro.md
      - Tooling: docs/developer_guide/tooling.md
      - Entities: docs/developer_guide/entities.md
      - REST API: docs/developer_guide/api.md
      - Modules:
        - Core: docs/developer_guide/modules/core.md
        - Products: docs/developer_guide/modules/products.md
        - Payment Gateways: docs/developer_guide/modules/payment_gateways.md
      - Contributing: docs/developer_guide/contributing.md
    - Licensing:
      - Software License: docs/license.md
      - Enterprise Agreement: docs/enterprise_agreement.md
  - Download: https://github.com/OBMS-Open-Business-Management-Software/core/releases/latest
  - Changelog: docs/changelog.md

